"""
On-policy SARSA training, as distinct from dqn_agent's off-policy Double
DQN. This is the actual algorithmic difference worth comparing:

  DQN target:   r + gamma * max_a' Q(s', a')      -- bootstraps off the
                BEST possible next action, regardless of what the policy
                actually does next (off-policy).
  SARSA target: r + gamma * Q(s', a')              -- bootstraps off the
                action the policy ACTUALLY TAKES next, including its own
                exploration (on-policy).

Practical consequence for THIS project: DQN training relied on a
hard-coded safety shield to intervene before bad actions in dangerous
states were ever executed and learned from -- disabling it revealed the
raw network had never genuinely learned self-preservation (see project
history). SARSA, being on-policy, learns the value of whatever the agent
actually does, exploration and mistakes included, with no shield here at
all -- a genuinely different lens on the same problem.

Implementation note: the target needs a_{t+1}, the action taken from
s_{t+1} -- which isn't known until the NEXT call to this module (act()
picks it, then game_events_occurred/end_of_round reports it as
self_action). So each step's SARSA update is completed one call later,
using a small pending buffer of exactly one transition. No large replay
buffer is used, deliberately: replaying old transitions generated by an
earlier, different version of the policy would undermine the "on-policy"
premise SARSA is built on. This is a single-sample online update, not a
batched one -- again a genuine, deliberate difference from DQN, not an
oversight.
"""
import json
import os

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

import events as e
from .callbacks import ACTION_TO_IDX, MODEL_FILE, state_to_features

GAMMA = 0.95
LR = 1e-3
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY_ROUNDS = 2_000
EPSILON_STEP = (EPSILON_START - EPSILON_END) / EPSILON_DECAY_ROUNDS

MOVED_CLOSER_TO_COIN = "MOVED_CLOSER_TO_COIN"
MOVED_FURTHER_FROM_COIN = "MOVED_FURTHER_FROM_COIN"
STAYED_PUT_IN_DANGER = "STAYED_PUT_IN_DANGER"
FLED_DANGER = "FLED_DANGER"
USELESS_BOMB_SPAM = "USELESS_BOMB_SPAM"
DANGER_THRESHOLD = 0.2

# Each `python main.py play --train 1 ...` call is a fresh process, so
# without persisting these, epsilon and the round counter would silently
# reset every single invocation -- exactly the bug found and fixed in
# dqn_agent early in this project, reproduced here by not having carried
# the fix over when this agent was first written. Fixed now, before any
# multi-burst pipeline depends on it working correctly.
STATE_FILE = "sarsa-train-state.json"
EPSILON_OVERRIDE_FILE = "sarsa-epsilon-override.txt"


def setup_training(self):
    self.optimizer = optim.Adam(self.model.parameters(), lr=LR)

    if os.path.isfile(STATE_FILE):
        with open(STATE_FILE) as f:
            state = json.load(f)
        self.epsilon = state.get("epsilon", EPSILON_START)
        self.rounds_played = state.get("rounds_played", 0)
        self.logger.info(f"Resumed training state: epsilon={self.epsilon:.3f}, "
                          f"rounds_played={self.rounds_played}")
    else:
        self.epsilon = EPSILON_START
        self.rounds_played = 0

    if os.path.isfile(EPSILON_OVERRIDE_FILE):
        with open(EPSILON_OVERRIDE_FILE) as f:
            self.epsilon = float(f.read().strip())
        os.remove(EPSILON_OVERRIDE_FILE)
        self.logger.info(f"Epsilon overridden for this burst: {self.epsilon:.3f}")

    # The one-step-delayed pending transition: (state_feat, action_idx, reward).
    # Completed once the NEXT action is known, using that as a_{t+1}.
    self.pending = None


def _nearest_coin_manhattan(game_state):
    if game_state is None or not game_state['coins']:
        return None
    x, y = game_state['self'][3]
    return min(abs(cx - x) + abs(cy - y) for cx, cy in game_state['coins'])


def _danger_here(game_state):
    if game_state is None:
        return 0.0
    return float(state_to_features(game_state)[8])


def _sarsa_update(self, state_feat, action_idx, reward, next_state_feat, next_action_idx):
    """Single-sample online SARSA update. next_state_feat=None means this
    was the terminal transition of the round (no bootstrap, target=reward
    alone)."""
    state_t = torch.tensor(state_feat, dtype=torch.float32, device=self.device).unsqueeze(0)
    q_values = self.model(state_t)
    q_sa = q_values[0, action_idx]

    if next_state_feat is None:
        target = torch.tensor(reward, dtype=torch.float32, device=self.device)
    else:
        with torch.no_grad():
            next_state_t = torch.tensor(next_state_feat, dtype=torch.float32,
                                         device=self.device).unsqueeze(0)
            next_q = self.model(next_state_t)[0, next_action_idx]
            target = reward + GAMMA * next_q

    loss = nn.functional.smooth_l1_loss(q_sa, target)
    self.optimizer.zero_grad()
    loss.backward()
    self.optimizer.step()


def _shaped_events(old_game_state, self_action, events):
    """Same reward-shaping ideas as dqn_agent (coin-seeking, danger-fleeing,
    bomb-spam), reused here since these are ordinary reward-function terms,
    not action-overriding rules -- fully compatible with pure RL."""
    old_dist = _nearest_coin_manhattan(old_game_state)
    was_in_danger = _danger_here(old_game_state) > DANGER_THRESHOLD
    if was_in_danger:
        events.append(STAYED_PUT_IN_DANGER if self_action in ('WAIT', 'BOMB') else FLED_DANGER)
    if self_action == 'BOMB' and e.INVALID_ACTION in events:
        events.append(USELESS_BOMB_SPAM)
    return old_dist


def game_events_occurred(self, old_game_state, self_action, new_game_state, events):
    old_dist = _shaped_events(old_game_state, self_action, events)
    new_dist = _nearest_coin_manhattan(new_game_state)
    if old_dist is not None and new_dist is not None:
        if new_dist < old_dist:
            events.append(MOVED_CLOSER_TO_COIN)
        elif new_dist > old_dist:
            events.append(MOVED_FURTHER_FROM_COIN)

    reward = reward_from_events(self, events)
    old_feat = state_to_features(old_game_state)
    new_feat = state_to_features(new_game_state)
    action_idx = ACTION_TO_IDX[self_action]

    if self.pending is not None:
        prev_feat, prev_action_idx, prev_reward = self.pending
        _sarsa_update(self, prev_feat, prev_action_idx, prev_reward, old_feat, action_idx)

    self.pending = (old_feat, action_idx, reward)
    # NOTE: this transition's own update happens on the NEXT call (or in
    # end_of_round if this was the last step), once a_{t+1} is known.


def end_of_round(self, last_game_state, last_action, events):
    _shaped_events(last_game_state, last_action, events)
    reward = reward_from_events(self, events)
    last_feat = state_to_features(last_game_state)
    last_action_idx = ACTION_TO_IDX[last_action]

    if self.pending is not None:
        prev_feat, prev_action_idx, prev_reward = self.pending
        # complete the previous transition using this round-ending action as a_{t+1}
        _sarsa_update(self, prev_feat, prev_action_idx, prev_reward, last_feat, last_action_idx)

    # the final transition itself is terminal: no bootstrap
    _sarsa_update(self, last_feat, last_action_idx, reward, None, None)
    self.pending = None

    self.rounds_played += 1
    self.epsilon = max(EPSILON_END, self.epsilon - EPSILON_STEP)
    self.logger.info(f"Round {self.rounds_played} done. epsilon={self.epsilon:.3f}")

    torch.save(self.model.state_dict(), MODEL_FILE)
    with open(STATE_FILE, "w") as f:
        json.dump({"epsilon": self.epsilon, "rounds_played": self.rounds_played}, f)


def reward_from_events(self, events: list) -> float:
    game_rewards = {
        e.COIN_COLLECTED: 1.0,
        e.KILLED_OPPONENT: 5.0,
        e.KILLED_SELF: -5.0,
        e.GOT_KILLED: -5.0,
        e.CRATE_DESTROYED: 0.3,
        e.INVALID_ACTION: -0.5,
        e.WAITED: -0.3,
        e.SURVIVED_ROUND: 0.5,
        MOVED_CLOSER_TO_COIN: 0.05,
        MOVED_FURTHER_FROM_COIN: -0.05,
        STAYED_PUT_IN_DANGER: -1.0,
        FLED_DANGER: 0.3,
        USELESS_BOMB_SPAM: -0.3,
    }
    reward_sum = sum(game_rewards.get(event, 0.0) for event in events if event is not None)
    self.logger.debug(f"Awarded {reward_sum:.2f} for events {events}")
    return reward_sum
